-- -------------------------------------------------------------
-- TablePlus 1.6(194)
--
-- https://tableplus.com/
--
-- Database: phpuk19
-- Generation Time: 2019-02-22 08:20:24.7800
-- -------------------------------------------------------------


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


DROP TABLE IF EXISTS `events`;
CREATE TABLE `events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `url_friendly_name` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `start_date` datetime NOT NULL,
  `end_date` datetime NOT NULL,
  `description` text COLLATE utf8mb4_general_ci,
  `stub` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `href` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `tz_continent` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `tz_place` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `attendee_count` int(11) DEFAULT NULL,
  `attending` tinyint(1) DEFAULT NULL,
  `event_average_rating` int(11) DEFAULT NULL,
  `event_comments_count` int(11) DEFAULT NULL,
  `tracks_count` int(11) DEFAULT NULL,
  `talks_count` int(11) DEFAULT NULL,
  `icon` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `location` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `images` json DEFAULT NULL,
  `tags` json DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `phinxlog`;
CREATE TABLE `phinxlog` (
  `version` bigint(20) NOT NULL,
  `migration_name` varchar(100) DEFAULT NULL,
  `start_time` timestamp NULL DEFAULT NULL,
  `end_time` timestamp NULL DEFAULT NULL,
  `breakpoint` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reminders`;
CREATE TABLE `reminders` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `talk_id` int(11) DEFAULT NULL,
  `phone_number` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `talks`;
CREATE TABLE `talks` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `talk_title` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `url_friendly_talk_title` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `talk_description` text COLLATE utf8mb4_general_ci,
  `type` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `start_date` datetime DEFAULT NULL,
  `duration` int(11) DEFAULT NULL,
  `stub` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `average_rating` int(11) DEFAULT NULL,
  `comments_enabled` tinyint(1) DEFAULT NULL,
  `comment_count` int(11) DEFAULT NULL,
  `starred` tinyint(1) DEFAULT NULL,
  `starred_count` int(11) DEFAULT NULL,
  `speakers` json DEFAULT NULL,
  `tracks` json DEFAULT NULL,
  `track_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `tracks`;
CREATE TABLE `tracks` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `event_id` int(11) DEFAULT NULL,
  `track_name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `track_description` text COLLATE utf8mb4_general_ci,
  `talks_count` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `events` (`id`, `name`, `url_friendly_name`, `start_date`, `end_date`, `description`, `stub`, `href`, `tz_continent`, `tz_place`, `attendee_count`, `attending`, `event_average_rating`, `event_comments_count`, `tracks_count`, `talks_count`, `icon`, `location`, `images`, `tags`, `created`, `modified`) VALUES ('1', 'PHP UK Conference 2019', 'php-uk-conference-2019', '2019-02-20 00:00:00', '2019-02-22 23:59:59', 'PHP UK is pleased to announce the 14th Annual PHP UK conference; a 2-day event with 3 great tracks held at at The Brewery, in the heart of the City of London.\n\nWith over 700 delegates, speakers, and sponsors, PHP UK conference aims to deliver fantastic up-to-date content about PHP and related web technologies in a comfortable and professional setting. There are countless networking opportunities to engage with international speakers and delegates, which makes the event one you won\'t want to miss.', NULL, 'https://www.phpconference.co.uk/', 'Europe', 'London', '25', '0', '0', '0', '0', '32', 'phpuk.jpg', 'The Brewery', '[]', '[\"technology\"]', '2019-02-21 12:51:22', '2019-02-21 12:51:22');

INSERT INTO `phinxlog` (`version`, `migration_name`, `start_time`, `end_time`, `breakpoint`) VALUES ('20190221121205', 'Initial', '2019-02-21 12:12:05', '2019-02-21 12:12:05', '0');

INSERT INTO `reminders` (`id`, `talk_id`, `phone_number`, `created`, `modified`) VALUES ('1', '20', '07854482836', '2019-02-21 21:59:21', '2019-02-21 21:59:21'),
('2', '26', '07854482836', '2019-02-21 21:59:21', '2019-02-21 21:59:21'),
('3', '25', '07854482836', '2019-02-21 21:59:21', '2019-02-21 21:59:21');

INSERT INTO `talks` (`id`, `talk_title`, `url_friendly_talk_title`, `talk_description`, `type`, `start_date`, `duration`, `stub`, `average_rating`, `comments_enabled`, `comment_count`, `starred`, `starred_count`, `speakers`, `tracks`, `track_id`) VALUES ('1', 'Workshop 1: Kubernetes By Example', 'workshop-1-kubernetes-by-example', 'Kubernetes, the flagship project from the Cloud Native Foundation, has become the de facto standard for running our container workloads. Unfortunately, Kubernetes is a fast moving, ever evolving, sea of complexity. From Pods to Deployments, ConfigMaps to Secrets, and PersistantVolumeClaims to StatefulSets; this workshop will get you on-course. In this workshop, David will walk you through a series of labs that will teach you everything you need to know to take your container based application and deploy it as a self-healing, redundant and resilient application on top of Kubernetes. Let\'s set sail.', 'Workshop', '2019-02-20 09:00:00', '360', '72cd3', '5', '1', '1', '0', '1', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/30603\", \"speaker_name\": \"David McKay\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1402\", \"track_name\": \"Workshop Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25893/tracks/1402\"}]', '6'),
('2', 'Workshop 2: BDD in Practice', 'workshop-2-bdd-in-practice', 'A tour of BDD best practices, applied in the PHP world. Behaviour Driven Development techniques help us to ensure that the code we\'re writing is solving real-world problems, and is software that matters. In this hands-on workshop we will build some simple software that fulfills a user\'s requirement; validate it\'s functionality using tools such as Behat, PHPUnit and PhpSpec; and learn how our test architecture can support our application\'s architecture.', 'Workshop', '2019-02-20 09:00:00', '360', '65813', '5', '1', '2', '0', '0', '[{\"speaker_name\": \"Ciaran McNulty\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1402\", \"track_name\": \"Workshop Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25894/tracks/1402\"}]', '6'),
('3', 'Pre-Conference Social', 'pre-conference-social', 'Wednesday night kicks off the conference with a night at the pub. We\'ll be meeting at Finch\'s pub on Finsbury Square (City Road) from 6pm til close for drinks, snacks, and a chance to meet other delegates before the conference starts.\r\n\r\nPlease rate this session for feedback to the event organisers about the event. There is a separate session to rate the evening\'s speaker.', 'Social Event', '2019-02-20 18:00:00', '360', 'd4306', '0', '1', '0', '0', '1', '[{\"speaker_name\": \"PHP UK Conference\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1408\", \"track_name\": \"Social\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25936/tracks/1408\"}]', '4'),
('4', 'Machine Learning and Trend Analysis in PHP', 'machine-learning-and-trend-analysis-in-php', 'Machine Learning and Trend Analysis in PHP', 'Talk', '2019-02-20 19:00:00', '30', '5d3e2', '0', '1', '0', '0', '0', '[{\"speaker_name\": \"Michael Cullum\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1408\", \"track_name\": \"Social\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25939/tracks/1408\"}]', '4'),
('5', 'Controlling the Variables', 'controlling-the-variables', 'As a kid, did you have ambitions for the future? \"When I grow up I want to become a ...\". Maybe you wanted to become a fireman, an astronaut, a nurse, a teacher, a police officer? As you grow up these ideas evolve and get replaced with actual ambitions, actual hopes and dreams. These might be entirely different than your childhood dreams. But how do you reach these goals? How do you accomplish these dreams? By listening to your parents, friends, or teachers? By doing it yourself? Or maybe you have given up and settled for a watered down version of the career and life you envisioned? People often attribute success to luck, and lack of success to incompetence. But what if I told you it\'s all about controlling the variables? Luck is something that you can control in a way. The more you figure out the context, the key players, the relationships, the values, and the rules of the ecosystem in which you want to succeed, the easier it is to gain from it. The more variables you control, the easier it is to find potential opportunities and to bank on them. Maybe you didn\'t get lucky, maybe you just saw it coming, and prepared yourself for it. In this keynote talk, Thijs is going to share his experiences, his hopes, his dreams, and how he applies a positive mental attitude to level up in his career, and in life in general. This is not a growth hacking talk, but a simple set of tips and tricks to succeed, even if it seems like the odds are stacked against you.', 'Keynote', '2019-02-21 09:00:00', '45', '89317', '4', '1', '5', '0', '2', '[{\"speaker_name\": \"Thijs Feryn\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1398\", \"track_name\": \"Main Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25880/tracks/1398\"}]', '2'),
('6', 'Massively Scaled High Performance Web Services with PHP', 'massively-scaled-high-performance-web-services-with-php', 'Over the years, software teams have questioned if PHP is a good choice for building web services. In this talk, I will share how we use PHP on the backend for Glu Mobile’s flagship mobile game Design Home, enabling it to regularly rank amongst the top free mobile games - both in downloads and grossing - since its launch in the Apple App Store and the Google Play Store in Q4 2016. Design Home reaches over 1 million daily active users, serving over 100,000 requests per minute while maintaining a user base of over 30 million players. To date, over 1 billion designs have been made by players. We will deep dive into the thought processes, development, testing and deployment strategy, showcasing what we have achieved with PHP and why we love it and rely on it. My goal is to share with the community that, when done the right way, PHP can be used to build and maintain reliable, massively-scalable and high-performance backends using web services.', 'Talk', '2019-02-21 10:15:00', '60', 'e81e7', '5', '1', '2', '0', '2', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/55757\", \"speaker_name\": \"Demin Yin\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1398\", \"track_name\": \"Main Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25881/tracks/1398\"}]', '2'),
('7', 'Database Encryption in a GDPR World', 'database-encryption-in-a-gdpr-world', '15 years ago, plain text password storing was normal with some using MD5. We look back now and wonder what we were thinking! With GDPR and people thinking more about personal details, its about time we caught up and started storing them securely. There are many uses for personal data and is often sought after by criminals for targeting people. How can you prevent your customers data being used in these attacks ? Encrypting your database is a fantastic way! PHP is the first language to have modern encryption built in to the core, This talk will show you how to use these methods to allow your data to be secure and also not lose the speed which you can currently search for this data in your application. This talk will touch on architecture and will be focused on MySQL although the same techniques can be used for any storage engine.', 'Talk', '2019-02-21 10:15:00', '60', '8654a', '5', '1', '2', '0', '0', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/30885\", \"speaker_name\": \"Scott Dutton\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1399\", \"track_name\": \"Mention Me Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25882/tracks/1399\"}]', '3'),
('8', 'Web Developer\'s HTTP Toolbox', 'web-developers-http-toolbox', 'You say \"toolbox\", I say \"treasure chest\". We work on the web building so much more than web pages but these rich, asynchronous applications can suffer from ailments that are difficult for us to see. This session is a tour through some of the best tools around for working with HTTP to observe interaction between components and diagnose problems. By knowing the tools at your disposal and the right job for each, you will be able to quickly and painlessly identify and fix HTTP-related problems - and then get to the pub on time! I mean, get the next thing done ;) Whether you\'re debugging a backend API, an asynchronous client request or an unexpected timeout, these are the tools you will want to have at hand.', 'Talk', '2019-02-21 10:15:00', '120', '8e688', '5', '1', '4', '0', '2', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/110\", \"speaker_name\": \"Lorna Mitchell\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1400\", \"track_name\": \"Velocity Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25883/tracks/1400\"}]', '5'),
('9', 'Running Your PHP Site on AWS Lambda', 'running-your-php-site-on-aws-lambda', 'Want to have immediate & easy website scaling, but also get rid of costly servers as they’re sitting idle 80% of the time waiting for visitors? Heard something about PHP and layers on AWS Lambda but have no idea what it means? You\'re not the only one! In this session we’ll get ourselves up-and-running with a PHP website on Lambda.', 'Talk', '2019-02-21 11:30:00', '60', 'f131a', '5', '1', '2', '0', '1', '[{\"speaker_name\": \"Neal Brooks\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1398\", \"track_name\": \"Main Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25884/tracks/1398\"}]', '2'),
('10', 'Dive Deep into Blockchain', 'dive-deep-into-blockchain', 'The blockchain is a hot new topic in the technology due to the rise of various cryptocurrencies, Bitcoin being a most prominent example. How does it work? What advantages does it give? What problems do they solve? What problems can be solved that way? I want you to dive with me into the immutable world of blocks where I will explain everything, from a simple hash, through Merkle trees, up to implementing your own blockchain.', 'Talk', '2019-02-21 11:30:00', '60', 'dc940', '0', '1', '0', '0', '0', '[{\"speaker_name\": \"Tomasz Kowalczyk\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1399\", \"track_name\": \"Mention Me Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25885/tracks/1399\"}]', '3'),
('11', 'Your App Lives on a Network - Networking for Web Developers', 'your-app-lives-on-a-network---networking-for-web-developers', 'Our job might be to build web applications, but we can\'t build apps that rely on networking if we don\'t know how these networks and the big network that connects them all (this thing called the Internet) actually work. I\'ll walk through the basics of networking, then dive a lot deeper (from TCP/UDP to IPv4/6, source/destination ports, sockets, DNS, switching, firewalling and even OSPF, VRRP and BGP). Prepare for an eye-opener when you realize how much a typical app relies on all of these (and many more) working flawlessly... and how you can prepare your app for failure in the chain.', 'Talk', '2019-02-21 13:30:00', '60', 'f21c9', '4', '1', '1', '0', '1', '[{\"speaker_name\": \"Wim Godden\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1398\", \"track_name\": \"Main Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25886/tracks/1398\"}]', '2'),
('12', 'Storing Non-Scalar Data', 'storing-non-scalar-data', 'In this presentation we will look at storing complex data in a single field. Many noSQL solutions are created around this (such as Redis’ lists, sets and hashes; MongoDB’s records), and many relational database now also support storing complex data in a single field through specific data types (such as PostGreSQL’s JSONB or hstore). Each of the different database engines support different things, and handle these data types in different ways. In this session we compare the different approaches to storage, indexing and interactions with these data types in different databases', 'Talk', '2019-02-21 13:30:00', '60', '33555', '0', '1', '0', '0', '0', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/30\", \"speaker_name\": \"Derick Rethans\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1399\", \"track_name\": \"Mention Me Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25887/tracks/1399\"}]', '3'),
('13', 'Deploying your first Micro-Service Application to Kubernetes', 'deploying-your-first-micro-service-application-to-kubernetes', 'Kubernetes is a very powerful container orchestration platform that is quickly gaining traction and gives you lots of benefits in deploying, running and scaling your microservice web application. But it has also a steep learning curve. In this workshop you will deploy and scale your first application which consists of multiple Micro-Services to Kubernetes and learn how you can use Persistent Storage. If you want to not just watch, but also program along yourself, have Git, Docker and the Kubernetes CLI kubectl as well as a IDE or Text Editor of your choice installed on your system.', 'Talk', '2019-02-21 13:30:00', '120', '91c8c', '5', '1', '3', '0', '1', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/11182\", \"speaker_name\": \"Bastian Hofmann\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1400\", \"track_name\": \"Velocity Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25888/tracks/1400\"}]', '5'),
('14', 'Getting Going with Automated Testing', 'getting-going-with-automated-testing', 'Automated testing is an incredibly useful tool for any developer. From emerging design with unit tests to preventing regression bugs with acceptance tests, getting a computer to run tests instead of testing manually is a huge step forward and saves vast amounts of time. Where do you start with automated testing? It\'s an intimidating topic and can be confusing to understand what all the techy speak means, let alone how you get going. But writing automated tests shouldn\'t be difficult, and can and should be part of your daily workflow once you understand exactly what to test, and how to test it. In this workshop, we\'ll introduce WHY and HOW you can get started with unit and acceptance tests, and touch on integration testing. By the end of the workshop, you\'ll understand how you can leverage automated testing in new and existing projects, and be ready to save time and energy when developing.', 'Talk', '2019-02-21 13:30:00', '120', '8fb0b', '0', '1', '0', '0', '0', '[{\"speaker_name\": \"Gary Hockin\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1401\", \"track_name\": \"Design Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25889/tracks/1401\"}]', '1'),
('15', 'MySQL 8.0 - Not Only Good, it\'s GREAT', 'mysql-80---not-only-good-its-great', 'Sick and tired of \"X technology is only good for starting out; after you do, move to Y\"? Good news - you don’t need to move away, you just need to get in further! In this talk, you\'ll learn about improvements in the newest version of the most used database in the world. What are Window Functions? How do you use CTEs? How can the new default encoding help me and what should I look for when upgrading versions?', 'Talk', '2019-02-21 14:45:00', '60', 'fd1fc', '5', '1', '2', '0', '1', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/3033\", \"speaker_name\": \"Gabriela D\'Ávila Ferrara\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1398\", \"track_name\": \"Main Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25890/tracks/1398\"}]', '2'),
('16', 'Learning The How\'s and Why\'s of Machine Learning', 'learning-the-hows-and-whys-of-machine-learning', 'Since it\'s founding, Tebex has processed over 18 million payments for games servers around the world. This is a rich data source, and one that we\'ve significantly under-used. We know there should be ways of using this data to improve our product and to make our merchant\'s lives easier - how and where to start, now that\'s a totally different question! Join Liam as he shares Tebex\'s initial experiences in experimenting with machine learning to use past data to prevent fraud in the future - different algorithms we\'ve tried, (many) failed experiments, the situation today and plans for the future.', 'Talk', '2019-02-21 14:45:00', '60', '4552f', '5', '1', '1', '0', '1', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/19590\", \"speaker_name\": \"Liam Wiltshire\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1399\", \"track_name\": \"Mention Me Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25891/tracks/1399\"}]', '3'),
('17', 'Everything is Awesome - The LEGOⓇ Approach to Being an Awesome Co-worker', 'everything-is-awesome---the-lego-approach-to-being-an-awesome-co-worker', '🎵Everything is cool when you’re part of a team!🎵 The Lego Movie came out almost 4 years ago, and it taught children everywhere the importance of teamwork. And what teamwork, and working in harmony, actually is. Let’s just hope that those lessons really stick with these kids. Because let’s be honest, we’re making a mess of it. But it’s not too late for us. We can learn from the Lego Movie as well. I’ll show you how you can help to make sure everyone feels safe and respected in your team and your company. How you can feel better being the unique person you are within your team. And how you can make your, and everyone else’s, life more awesome!', 'Talk', '2019-02-21 16:15:00', '45', '368e6', '5', '1', '1', '0', '2', '[{\"speaker_name\": \"Paul Verbeek-Mast\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1398\", \"track_name\": \"Main Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25892/tracks/1398\"}]', '2'),
('18', 'Mid-Conference Social', 'mid-conference-social', 'Thursday evening we\'ll be hosting our main social event at the conference venue.\r\n\r\nAfter talks finish at the end of the day we\'ll move to the King George for drinks, snacks and chat from 6pm til 9pm.\r\n\r\nWe\'ll be serving some free drinks and beef burgers, veggie burgers, chips and nibbles.', 'Social Event', '2019-02-21 17:00:00', '180', '79bfe', '0', '1', '0', '0', '3', '[]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1408\", \"track_name\": \"Social\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25937/tracks/1408\"}]', '4'),
('19', 'From Good to SOLID - Becoming a Better PHP Developer', 'from-good-to-solid---becoming-a-better-php-developer', 'Working with companies from early-stage startups to Fortune 500, I\'ve experienced both the struggle of continuing someone else\'s work and the joy of it. The difference is only in their approach towards the design of their code. It\'s a minor effort if done on time, with a huge impact on the overall development of the software. In this presentation, we\'ll focus on what distinguishes a good developer from a strong one and learn how to stand out from the crowd. After this presentation, you\'d understand how to incorporate the SOLID principles in your daily work and design your code for extendibility. You\'d learn how to write code in a way that will make it easy to go back to a feature you developed a year ago and extend it with additional functionality in minutes, not hours.', 'Keynote', '2019-02-22 09:00:00', '45', '2bf0c', '0', '0', '0', '0', '3', '[{\"speaker_name\": \"Katerina Trajchevska\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1398\", \"track_name\": \"Main Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25895/tracks/1398\"}]', '2'),
('20', 'Microservices Gone Wrong', 'microservices-gone-wrong', 'Microservices are the latest architectural trend to take the PHP community by storm. Is it a good pattern? How can you use it effectively? In this talk, we\'ll explore real world experience building out a large scale application based around microservices - what worked really well, what didn\'t work at all, and what we learned along the way. Spoiler alert - we got a lot wrong.', 'Talk', '2019-02-22 10:15:00', '60', '715ac', '0', '0', '0', '0', '3', '[{\"speaker_name\": \"Anthony Ferrara\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1398\", \"track_name\": \"Main Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25896/tracks/1398\"}]', '2'),
('21', 'Test to Break Principles', 'test-to-break-principles', 'The talk aims to highlight the importance of testing, why developers must spend more of their time testing, how testing generates more robust applications and why testing makes developers\' lives easier. The talk is based around a live coding demo. The talk will: Explain the difference between tests that prove an application works and tests which aim to break the application logic - Highlight how test to break principles force developers to introduce logic to handle unexpected behaviour - Show how test to break principles result in more robust applications as developers write code that can only be used in one way - Encourage developers to apply test to break principles to all types of tests, including manual tests', 'Talk', '2019-02-22 10:15:00', '60', 'a3684', '0', '0', '0', '0', '0', '[{\"speaker_name\": \"Rob Waller\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1399\", \"track_name\": \"Mention Me Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25897/tracks/1399\"}]', '3'),
('22', 'LAMP ❤️ AWS', 'lamp--aws', 'There are a great many reasons your application can benefit from moving to the cloud, but enough requirements for retraining, uncertainty around cost or complexity and just plain worry about what can go wrong to delay or prevent such a move. When my business moved to the cloud we learned that there are ways around many of these challenges, allowing you to move your application in a way which might not be best practice but which works and gives you a solid platform from which to advance and improve your cloud implementation. In this tutorial we\'ll look at key building blocks to put a LAMP application onto AWS, what might cause problems for your individual use cases and how to mitigate these. As well as basic plans to get you started we\'ll look at pathways to modify your application and train your team to take more advantage of cloud native features and adhere to infrastructure and security best practices in a way which allows you to keep running your team and your business.', 'Talk', '2019-02-22 10:15:00', '120', 'f77b6', '0', '0', '0', '0', '0', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/16566\", \"speaker_name\": \"M1ke\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1400\", \"track_name\": \"Velocity Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25898/tracks/1400\"}]', '5'),
('23', 'A Practical Introduction to Strategic Domain Driven Design', 'a-practical-introduction-to-strategic-domain-driven-design', 'Knowing how to do things right is half the battle. Knowing how to do the right thing is the under appreciated but essential other half. In this workshop we\'ll learn how to discover the language of our clients. We will gracefully evolve our understanding from nothing to something and use various modelling tools to grow our understanding of the problem. If you want to have better conversations, make more useful models, and have the optimal preparation for writing code, then this is the workshop for you. Topics include context mapping, event storming, and value mapping.', 'Talk', '2019-02-22 10:15:00', '120', '1e727', '0', '0', '0', '0', '0', '[{\"speaker_name\": \"Pim Elshoff\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1401\", \"track_name\": \"Design Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25899/tracks/1401\"}]', '1'),
('24', 'Does Your Code Measure Up?', 'does-your-code-measure-up', 'After days, weeks, or months of coding many developers don’t know how to gauge the quality of their code. I’ll introduce tools to grade, benchmark, and analyze PHP code in an automated fashion allowing developers to write better quality software. Then I’ll explain key metrics to help understand what may need to be refactored, and use code smells to point out bugs before end-users discover them. Attendees will see how to use these tools, know where to find them, and be able to implement them in their own workflows.', 'Talk', '2019-02-22 11:30:00', '60', 'a1c5a', '0', '0', '0', '0', '1', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/287\", \"speaker_name\": \"Adam Culp\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1398\", \"track_name\": \"Main Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25900/tracks/1398\"}]', '2'),
('25', 'More Secrets of Cryptography', 'more-secrets-of-cryptography', 'Alice and Bob have covered the basics of secure communication but cryptography can offer us more than this. After a brief refresher on the basics, we\'ll take a look at some of these other aspects of cryptography including hash functions, elliptic curves and quantum cryptography. Then we\'ll take a look at some practical applications answering questions such as: can I trust a web of trust? or should I use a block chain for this?', 'Talk', '2019-02-22 11:30:00', '60', 'f5de4', '0', '0', '0', '0', '0', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/27125\", \"speaker_name\": \"Christopher Riley\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1399\", \"track_name\": \"Mention Me Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25901/tracks/1399\"}]', '3'),
('26', 'From Dev to Prod with GitLab CI', 'from-dev-to-prod-with-gitlab-ci', 'Continuous Delivery Pipeline as code is key helping you to ensure long term maintainability. Treating your pipeline as code helps you to version it in your SCM of choice, makes changes easily traceable and lets anyone on your team make required changes. In this session I will show you how we build and maintain our Continuous Delivery pipeline using tools like GitLab CI, Docker, Nexus and Traefik. Together we will take a deep dive into the GitLab CI Build Pipelines to build and deploy docker containers to dev, stage and production environments.', 'Talk', '2019-02-22 13:30:00', '60', '4582b', '0', '0', '0', '0', '0', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/2211\", \"speaker_name\": \"Stephan Hochdörfer\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1398\", \"track_name\": \"Main Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25902/tracks/1398\"}]', '2'),
('27', 'Get GOing with a New Language', 'get-going-with-a-new-language', 'Learning more than one programming language is key to becoming a better developer. It is like adding a new tool to your toolbox. The more tools you have, the easier and quicker you’ll be able to tackle whatever job you need to do. You’ll also be able to use the right tool for the job, and who doesn’t like that?! I picked up Go (golang) a few years ago as it was becoming more popular among developers. Coming from a PHP background, I had no idea what channels or goroutines were or how is concurrency different from parallelism. I’ve got to say, it was a whole new world. Very different, but very cool. I was hooked! By happy coincidence, my company was looking to rewrite a legacy PHP app in Go. It was over 2000 lines of procedural and messy PHP4 with more downtime than I’m willing to admit to. I took on this project, and soon enough we had a much faster, more maintainable and much more reliable app for our customers. Go gave us options we would not have in PHP. The goal of this talk is to give you a good idea of what Go is and how it compares with PHP. We’ll look at the language itself as well as the tooling and communities around it. Even if you’re not sold on Go by the end of it, I hope you’ll leave inspired to go out there and learn whatever language you wanted to look into next.', 'Talk', '2019-02-22 13:30:00', '60', '1f769', '0', '0', '0', '0', '1', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/41575\", \"speaker_name\": \"Kat Zien\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1399\", \"track_name\": \"Mention Me Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25903/tracks/1399\"}]', '3'),
('28', 'Transparent Docker', 'transparent-docker', 'Keeping your environments in sync has been a challenge for software development for a long time. Developers tend to install their own versions of languages, databases, services etc. Doing so manually results in not only inconsistencies between dev and prod, but also from developer to developer, resulting in the always wonderful \"\"It works on my machine\"\" syndrome. Various tools have strived to solve this problem: MAMP, XAMP, VirtualBox, Vargrant, Puppet, Chef, homestead, etc. These are all steps in the right direction, but they\'re often heavy and require developers to learn new skills to work with them. In this talk, I\'ll be showing you how to Dockerize a new or existing project in such a way that the developers that use the project barely even know they are using Docker. Getting a new dev up to speed on a new project with a factory fresh machine is literally just a matter of installing Docker and check out the source code. That\'s it! Some of the benefits you\'ll see from using this approach:\r\n\r\nOnboard new devs in minutes.\r\nHave projects with unique (often incompatible) dependencies on a single machine.\r\nDockerized environment that acts like natively installed tools\r\nVersion locking of the tech stack\r\nUpdates to dependencies automatically distributed to other developers\r\nEasily extended into CI/CD', 'Talk', '2019-02-22 13:30:00', '120', '9f51e', '0', '0', '0', '0', '1', '[{\"speaker_name\": \"Donald Tyler\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1400\", \"track_name\": \"Velocity Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25904/tracks/1400\"}]', '5'),
('29', 'Best Practices for Crafting High Quality PHP Apps', 'best-practices-for-crafting-high-quality-php-apps', 'This prototype works, but it’s not pretty, and now it’s in production. That legacy application really needs some TLC. Where do we start? When creating long lived applications, it’s imperative to focus on good practices. The solution is to improve the whole development life cycle; from planning, better coding and testing, to automation, peer review and more. In this tutorial, we’ll take a deep dive into each of these areas, looking at how we can make positive, actionable change in our workflow. This workshop intends to improve your skills in planning, documenting, some aspects of development, testing and delivery of software for both legacy and greenfield projects. The workshop is made up of multiple exercises, allowing dynamic exploration into the various aspects of the software development life cycle. In each practical exercise, we\'ll brainstorm and investigate solutions, ensuring they are future-proofed, well tested and lead to the ultimate goal of confidence in delivering stable software.', 'Talk', '2019-02-22 13:30:00', '120', 'c5748', '0', '0', '0', '0', '0', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/22381\", \"speaker_name\": \"James Titcumb\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1400\", \"track_name\": \"Velocity Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25905/tracks/1400\"}]', '5'),
('30', 'Hybrid Databases: How De-normalizing Your Data with JSON Can Boost Query Performance', 'hybrid-databases-how-de-normalizing-your-data-with-json-can-boost-query-performance', 'Database joins can be expensive and you can reduce dives into the indexes/data by using JSON columns. By loading data kept in smaller \'stub\' tables into main tables it is possible to minimize joins for simple data like address, phone numbers, and the like in schemaless JSON documents. Yes, third normal form or better has advantages at many levels but it is a design that is costly for many-to-many relations! It is very easy to refactor data is is often stagnant or infrequently updated to take advantage of hybrid SQL/NoSQL databases to greatly increase overall query performance plus increase code readability. This approach can completely change your ideas on data architecture and provide easy mutability for future changes.\r\n\r\nSlides at https://slideshare.net/davidmstokes', 'Talk', '2019-02-22 14:45:00', '60', '698a3', '0', '0', '0', '0', '0', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/16715\", \"speaker_name\": \"Dave Stokes\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1398\", \"track_name\": \"Main Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25906/tracks/1398\"}]', '2'),
('31', 'I deploy on Fridays (and maybe you should too)', 'i-deploy-on-fridays-and-maybe-you-should-too', 'Have you ever heard someone say “Don’t deploy on Friday”? I used to say that too! Learn about resilience and operability, deployments, pipelines and continuous testing. Discover trunk based development, pair programming and best practices, and gain the confidence to deploy any day of the week!', 'Keynote', '2019-02-22 16:15:00', '45', '6c25b', '0', '0', '0', '0', '2', '[{\"speaker_uri\": \"https://api.joind.in/v2.1/users/13883\", \"speaker_name\": \"Michiel Rook\"}]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1398\", \"track_name\": \"Main Track\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25907/tracks/1398\"}]', '2'),
('32', 'Post-Conference Social', 'post-conference-social', 'Friday night will be our post conference social. We\'ve got some fun plans in the works, so stay tuned for more info coming soon!', 'Social Event', '2019-02-22 17:00:00', '180', 'ec3e8', '0', '0', '0', '0', '1', '[]', '[{\"track_uri\": \"https://api.joind.in/v2.1/tracks/1408\", \"track_name\": \"Social\", \"remove_track_uri\": \"https://api.joind.in/v2.1/talks/25938/tracks/1408\"}]', '4');

INSERT INTO `tracks` (`id`, `event_id`, `track_name`, `track_description`, `talks_count`) VALUES ('1', '1', 'Design Track', 'Design Track', '2'),
('2', '1', 'Main Track', 'Main Track', '12'),
('3', '1', 'Mention Me Track', 'Mention Me Track', '7'),
('4', '1', 'Social', 'Social', '4'),
('5', '1', 'Velocity Track', 'Velocity Track', '5'),
('6', '1', 'Workshop Track', 'Workshop Track', '2');




/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;